apiVersion: v2
name: "cray-hms-bss"
version: 3.3.3
description: "Kubernetes resources for cray-hms-bss"
home: "https://github.com/Cray-HPE/hms-bss-charts"
sources:
  - "https://github.com/Cray-HPE/hms-bss"
dependencies:
  - name: cray-service
    version: "~12.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "~1.3"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "1.33.0"  # update pprof image version below as well
annotations:
  artifacthub.io/images: |-
    - name: cray-bss-pprof
      image: artifactory.algol60.net/csm-docker/stable/cray-bss-pprof:1.32.0
  artifacthub.io/license: "MIT"
